/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqli_zafiyet.UI;

import java.awt.Color;
import sqli_zafiyet.entity.Customer;
import sqli_zafiyet.repository.CustomerDao;

/**
 *
 * @author kaan
 */
public class MusteriSayfasi extends javax.swing.JPanel {

    /**
     * Creates new form MusteriSayfasi
     */
    public MusteriSayfasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbxCustomerName = UI_CONSTS.createTextField("");
        jButton1 = UI_CONSTS.createButton((ae) -> {
            getByCustomerName();
        }, Color.YELLOW);
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblEmpty = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(3, 2));

        tbxCustomerName.setText("Müşteri adına göre arayın");
        add(tbxCustomerName);

        jButton1.setText("Müşteri adına göre ara");
        add(jButton1);

        lblName.setText("jLabel1");
        add(lblName);

        lblEmail.setText("jLabel3");
        add(lblEmail);

        lblAddress.setText("jLabel4");
        add(lblAddress);

        lblEmpty.setText("jLabel2");
        add(lblEmpty);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpty;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField tbxCustomerName;
    // End of variables declaration//GEN-END:variables

    void getByCustomerName() {
        CustomerDao customerDao = new CustomerDao();

        String customerName = tbxCustomerName.getText();

        Customer customer = customerDao.getByCustomerName(customerName);

        lblEmail.setText(customer.getEmail());
        lblName.setText(customer.getCustomerName());
        lblAddress.setText(customer.getPhoneNumber());
        lblEmpty.setText(customer.getId() + "");

    }

}
